name: solhycool-deployment

volumes:
  airflow_logs:
  airflow_plugins:

services:
  airflow:
    container_name: solhycool-airflow
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    # command: tail -f /dev/null
    working_dir: ${AIRFLOW_HOME}
    command: airflow standalone
    volumes:
      - airflow_logs:${AIRFLOW_HOME}/logs
      - airflow_plugins:${AIRFLOW_HOME}/plugins
      - ./deployment/config:${AIRFLOW_HOME}/config
      - ./deployment/dags:${AIRFLOW_HOME}/dags
      - ./data:${AIRFLOW_HOME}/data:ro
      - ./simulation:${AIRFLOW_HOME}/simulation
    ports:
      - "8080:8080"